<?
$arLink = [
    'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-spf50-s-omega-3-6-9-i-termalnoy-vodoy-150-ml/' => 'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-spf50-s-omega-3-6-9-i-termalnoy-vodoy-150-ml-rb/',
    'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-d-detey-spf50-s-omega-3-6-9-i-term-vodoy-150-ml-rb/' => 'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-d-detey-spf50-s-omega-3-6-9-i-termalnoy-vodoy-150-ml/',
    'https://all.bh.by/catalog/ukhod-za-litsom/mitselyarnaya-voda/garnier-mitsellyarnaya-voda-chistaya-kozha-400-ml-new/' => 'https://all.bh.by/catalog/ukhod-za-litsom/mitselyarnaya-voda/garnier-mitsellyarnaya-voda-chistaya-kozha-400-ml/',
    'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/sredstva-dlya-chistki-kovrov-mebeli/vanish-gold-aktivnaya-pena-dlya-chistki-kovrov-chistota-i-svezhest-600-ml/' => 'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/sredstva-dlya-chistki-kovrov-mebeli/vanish-gold-aktivnaya-pena-dlya-chistki-kovrov-chistota-i-svezhest-600-ml-15704/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-krem-blesk-dlya-kozhi-bestsvetnyy-75-ml/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-krem-blesk-dlya-kozhi-bestsvetnyy-75-ml-21577/',
    'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-d-litsa-i-zony-dekolte-solntsezashchitnyy-spf30-50-ml-rb/' => 'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-d-litsa-i-zony-dekolte-solntsezashchitnyy-spf30-50-ml/',
    'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-d-litsa-i-zony-dekolte-solntsezashchitnyy-spf50-50-ml-rb/' => 'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-d-litsa-i-zony-dekolte-solntsezashchitnyy-spf50-50-ml/',
    'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-spf15-s-omega-3-6-9-i-termalnoy-vodoy-150-ml/' => 'https://all.bh.by/catalog/ukhod-za-telom/sredstva-dlya-zagara/solntsezashchitnye-sredstva/librederm-bronzeada-krem-solntsezashchitnyy-spf15-s-omega-3-6-9-i-termalnoy-vodoy-150-ml-rb/',
    'https://all.bh.by/catalog/ukhod-za-telom/dezodoranty-antiperspiranty-sprei-dlya-muzhchin/axe-deo-aerozol-gold-150-ml-67658678/' => 'https://all.bh.by/catalog/ukhod-za-telom/dezodoranty-antiperspiranty-sprei-dlya-muzhchin/axe-deo-aerozol-gold-150-ml/',
    'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/chernyy-zhemchug-bio-programma-krem-dlya-litsa-36-50-ml-1102989-65500816-32465628/' => 'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/chernyy-zhemchug-bio-programma-krem-dlya-litsa-36-50-ml/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-krem-dlya-obuvi-tuba-s-gubkoy-chernyy-75-ml-21564/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-krem-dlya-obuvi-tuba-s-gubkoy-chernyy-75-ml/',
    'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/chernyy-zhemchug-bio-programma-krem-dlya-litsa-46-50-ml/' => 'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/chernyy-zhemchug-bio-programma-krem-dlya-litsa-46-50-ml-18695/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-stirki/zhidkie-sredstva-dlya-stirki/washing-tone-sr-vo-d-stirki-roskoshnyy-chernyy-1500-ml-new-s-pro/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-stirki/zhidkie-sredstva-dlya-stirki/washing-tone-sredstvo-d-stirki-roskoshnyy-chernyy-/',
    'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/chistyashchie-sredstva/mr-muscle-ekspert-dlya-kukhni-energiya-tsitrusa-sprey-500-ml-15909/' => 'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/chistyashchie-sredstva/mr-muscle-ekspert-dlya-kukhni-energiya-tsitrusa-sprey-500-ml/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-ot-nasekomykh/mosquitall-zhidkost-45-nochey-universalnaya-zashchita-ot-komarov/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-ot-nasekomykh/mosquitall-zhidkost-45-nochey-universalnaya-zashchita-ot-komarov-19318/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/dividik-ochistitel-pennyy-dlya-kozhi-zamshi-velyura-aerozol-125-ml/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/dividik-ochistitel-pennyy-dlya-kozhi-zamshi-velyura-aerozol-125-ml-19395/',
    'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/l-oreal-dermo-expertise-krem-ukhod-dlya-litsa-vozrast-ekspert-35-nochnoy-50-ml/' => 'https://all.bh.by/catalog/ukhod-za-litsom/krem-dlya-litsa/l-oreal-dermo-expertise-krem-ukhod-dlya-litsa-vozrast-ekspert-35-nochnoy-50-ml-20886/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-gubka-dlya-kozhi-bolshaya-bestsvetnaya-19414/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-gubka-dlya-kozhi-bolshaya-bestsvetnaya/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-gubka-dlya-kozhi-bestsvetnaya-standard-19420/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-obuvi/twist-casual-gubka-dlya-kozhi-bestsvetnaya-standard/',
    'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-stirki/zhidkie-sredstva-dlya-stirki/washing-tone-sr-vo-d-stirki-delikatnyy-ukhod-1500-ml-new-s-pro/' => 'https://all.bh.by/catalog/chistota-v-dome/sredstva-dlya-stirki/zhidkie-sredstva-dlya-stirki/washing-tone-sredstvo-d-stirki-delikatnyy-ukhod/',
    'https://all.bh.by/catalog/kosmetika/kosmetika-dlya-litsa/tonalnyy-krem/filter/brands-is-l\'oreal/apply/' => 'https://all.bh.by/catalog/kosmetika/kosmetika-dlya-litsa/tonalnyy-krem/filter/brands-is-l%27oreal/apply/',
    'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/tualetnye-bloki/tualetnyy-utenok-podvesnoy-ochistitel-unitaza-morskoy-55-ml-655401/' => 'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/tualetnye-bloki/tualetnyy-utenok-podvesnoy-ochistitel-unitaza-morskoy-55-ml/',
    'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/chistyashchie-sredstva/mr-muscle-dlya-vannoy-5v1-sprey-500-ml-15908/' => 'https://all.bh.by/catalog/chistota-v-dome/chistyashchie-i-moyushchie-sredstva/chistyashchie-sredstva/mr-muscle-dlya-vannoy-5v1-sprey-500-ml-15907/',
    'https://all.bh.by/catalog/chistota-v-dome/khozyaystvennye-tovary/perchatki/azur-perchatki-rezinovye-l-new/' => 'https://all.bh.by/catalog/chistota-v-dome/khozyaystvennye-tovary/perchatki/azur-perchatki-rezinovye-l/',
    'https://all.bh.by/catalog/gigiena/ukhod-za-polostyu-rta/zubnye-pasty/silcamed-zubnaya-pasta-arctic-white-100-ml-21395/' => 'https://all.bh.by/catalog/gigiena/ukhod-za-polostyu-rta/zubnye-pasty/silcamed-zubnaya-pasta-arctic-white-100-ml/'
];

if (array_key_exists('https://all.bh.by'.$APPLICATION->GetCurPage() , $arLink)) {
    echo '<link rel="canonical" href="'.$arLink['https://all.bh.by'.$APPLICATION->GetCurPage()].'"/>';
}