<?if (!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();
/*
 * SLIDER
 */
define(SLIDER_IBLOCK_ID_S2, 12);

/*
 * NEWS
 */
define(NEWS_IBLOCK_ID_S2, 13);

/*
 * BRANDS
 */
define(BRANDS_IBLOCK_ID, 7);
define(BRANDS_PROPERTY_SITE_CODE, "UF_SITE");
define(BRANDS_PROPERTY_SITE_ID, 38);

/*
 * LINKS
 */
define(LINKS_IBLOCK_ID_S2, 16);

/*
 * CATALOG
 */
define(CATALOG_IBLOCK_ID, 2);
define(CATALOG_PROPERTY_SITE_CODE, "UF_SITE");
define(CATALOG_PROPERTY_SITE_ID, 39);
define(CATALOG_IBLOCK_ID_FITER_SEO_DATA, 22);
define(CATALOG_CUSTOM_CERT_ENUM, 4743);
define(CATALOG_CUSTOM_CERT_NON_NOMINEE, 32297);